### PR TITLE
Build with latest Quarto

### PR DESCRIPTION
**Pull request by stefanv**
Build almost goes through, but still fails at the last compilation step with:

```
Traceback (most recent call last):
  File "/home/stefan/p/resampling/resampling-roam/resampling-with/source/noteout-filter-pre", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/stefan/envs/py311/lib64/python3.11/site-packages/noteout/filter_pre.py", line 13, in main
    PreFilter.main(doc=doc)
  File "/home/stefan/envs/py311/lib64/python3.11/site-packages/noteout/nb_only.py", line 33, in main
    return pf.run_filter(cls.action,
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stefan/envs/py311/lib64/python3.11/site-packages/panflute/io.py", line 227, in run_filter
    return run_filters([action], *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stefan/envs/py311/lib64/python3.11/site-packages/panflute/io.py", line 200, in run_filters
    doc = load(input_stream=input_stream)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stefan/envs/py311/lib64/python3.11/site-packages/panflute/io.py", line 58, in load
    doc = json.load(input_stream, object_hook=from_json)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/json/__init__.py", line 359, in loads
    return cls(**kw).decode(s)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stefan/envs/py311/lib64/python3.11/site-packages/panflute/elements.py", line 1424, in from_json
    assert (len(data) == 1) or (len(data) == 2 and 'c' in data)
```

### CODE REVIEW

**Comment by matthew-brett** [comment]
Is that right - all the pages need to be `.qmd` now?   Why?

**Comment by stefanv** [comment]
> Is that right - all the pages need to be `.qmd` now? Why?

I could not see an obvious way to get the engine binding correct without it:

https://quarto.org/docs/computations/execution-options.html#engine-binding

**Comment by matthew-brett** [comment]
That's odd - do we want the Knitr or the Jupyter engine?  I guess Knitr?   I guess the alternative is to put `engine: knitr` in the metadata of the pages?    Does Jupytext deal as well with `.qmd` files as `.Rmd` files?  If so, I guess `.qmd` files are fine.

**Comment by stefanv** [comment]
I specifically switched away from knitr, because it did not preserve Python variables from "cell" to "cell". But perhaps there is a better way to configure knitr instead?

**Comment by matthew-brett** [comment]
Ouch - very recent Quarto JSON problem : https://github.com/quarto-dev/quarto-cli/issues/5443

**Comment by matthew-brett** [comment]
Knitr works fine for me in the <https://github.com/matthew-brett/test-quarto-2> . What exact problems do you get with the `.Rmd` files?

**Comment by stefanv** [comment]
It said np not found, when it was defined in a preceding cell.

**Comment by matthew-brett** [comment]
That can happen with a corrupt cache - did you try a 'git clean -fxd`?

**Comment by stefanv** [comment]
Reverting in favor of:

- using filters as a submodule
- not using qmd files, since knittr is supposed to work fine; may have been a caching issue.

**Pull request closed without merging**
